# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'terminal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(629, 400)
        MainWindow.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.commandInput = QtWidgets.QLineEdit(self.centralwidget)
        self.commandInput.setGeometry(QtCore.QRect(10, 375, 571, 20))
        self.commandInput.setObjectName("commandInput")
        self.terminal_box = QtWidgets.QTextEdit(self.centralwidget)
        self.terminal_box.setGeometry(QtCore.QRect(10, 30, 571, 341))
        self.terminal_box.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.terminal_box.setObjectName("terminal_box")
        self.setPref = QtWidgets.QPushButton(self.centralwidget)
        self.setPref.setGeometry(QtCore.QRect(590, 360, 31, 31))
        self.setPref.setObjectName("setPref")
        self.terminal_bg = QtWidgets.QLineEdit(self.centralwidget)
        self.terminal_bg.setGeometry(QtCore.QRect(590, 70, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setKerning(True)
        self.terminal_bg.setFont(font)
        self.terminal_bg.setObjectName("terminal_bg")
        self.text_color = QtWidgets.QLineEdit(self.centralwidget)
        self.text_color.setGeometry(QtCore.QRect(590, 140, 31, 21))
        self.text_color.setObjectName("text_color")
        self.bg_color_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.bg_color_edit.setGeometry(QtCore.QRect(590, 210, 31, 21))
        self.bg_color_edit.setObjectName("bg_color_edit")
        self.sizeEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.sizeEdit.setGeometry(QtCore.QRect(590, 280, 31, 21))
        self.sizeEdit.setObjectName("sizeEdit")
        self.newMenu = QtWidgets.QPushButton(self.centralwidget)
        self.newMenu.setGeometry(QtCore.QRect(10, 4, 89, 21))
        self.newMenu.setObjectName("newMenu")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Command Tool"))
        self.setPref.setText(_translate("MainWindow", "OK"))
        self.terminal_bg.setPlaceholderText(_translate("MainWindow", "T"))
        self.text_color.setPlaceholderText(_translate("MainWindow", "C"))
        self.bg_color_edit.setPlaceholderText(_translate("MainWindow", "B"))
        self.sizeEdit.setPlaceholderText(_translate("MainWindow", "S"))
        self.newMenu.setText(_translate("MainWindow", "New Page"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
